### ISSUE TITLE
5.0.4 changes

### ISSUE THREAD

**Issue by jadamcrain** [berkowski/tokio-serial#59]
Hey @estokes. I was just looking to see what changed in 5.0.3 -> 5.0.4 and it looks like all you did was bump `mio-serial` from 5.0.2 to 5.0.3?

I might be missing something, but if nothing was added in mio-serial 5.0.4 that tokio-serial requires, users will pick up this patch release automatically, no?

```
[dependencies.mio-serial]
version = "5.0.2"
```

The dependency above means **>= 5.0.2**.  Users will automatically bump to mio-serial 5.0.3 if they run `cargo update`.

In general, you want your cargo.toml to depend on the minimum version of a crate that is API compatible. If people are following semver, this hopefully means that you never have depend on anything other than major or minor version numbers.

Am I missing something?

**Comment by estokes** [comment]
This was a very minor release intended to make sure that it was pulling in mio-serial 5.0.4 at a minimum, because mio-serial was updated to depend on a new nix version. I realize that it wasn't strictly necessary to make a release, and that the new mio serial version would be pulled in automatically in most cases, but I did make the release anyway out of an abundance of caution. Did it cause problems for you, or were you just curious?

**Comment by jadamcrain** [comment]
No problems. It's more just that we watch our dependencies very carefully. My comment was more just reaching out to understand the reasons and see if I could save you time in the future with my feedback.

This library (and serial/mio-serial) has become critical to two of our product offerings. If we can help with any maintenance tasks or small github sponsorship let me know.

**Comment by estokes** [comment]
Please reach out to me at eestokes@pm.me we can discuss further. I'm happy to learn that someone cares, I do try to take this maintenance role seriously. I have for a while meant to do a comprehensive code review of both these modules, since I didn't write the code, I'm just a user like you who stepped up to maintain it after the original author didn't have the time, it's critical to some of my projects as well. Maybe I'll get motivated to do that now :-)

**Comment by jadamcrain** [comment]
Done! ty.
